package dies

import (
	"fmt"
	"os"

	"github.com/datapointchris/forge/v7/reconcile"
)

// Markdownlintignore asserts the standard .markdownlintignore entries.
//
// Append-only like Gitignore, and for the same reason: the contents are
// legitimately per-repo — logsift ignores PLANNING.md, theme ignores its
// analysis docs — so a plain file deploy would destroy them.
//
// This is sync-markdownlintignore and has-clean-markdownlintignore in one, and
// the merge settles the disagreement between them rather than picking a side.
// The sync seeded the entry into every repo; the check deliberately passed a
// repo with no CHANGELOG.md, its own comment naming the reason — "failing
// 50-odd repos that will never cut a release is how a scorecard trains
// skimming" — and calling how widely to seed it an open question.
//
// Both are right about their own verb, which is why one verb could not hold
// them. The entry is Automatic drift whether or not a CHANGELOG exists, so it
// appears in plan (apply would add it: true) and never in check (something is
// wrong: false). No policy call was needed; the Repair split answers it.
type Markdownlintignore struct{}

func (Markdownlintignore) Name() string { return "markdownlintignore" }

func (Markdownlintignore) Description() string {
	return "Ensure the standard .markdownlintignore entries are present, with the reason written above each one. Append-only, never a rewrite."
}

func (Markdownlintignore) Tags() []string {
	return []string{"markdownlint", "changelog", "standardization", "golden-path"}
}

// Every hand-written .markdownlintignore in the fleet says why its entries are
// there, and a reader hitting a bare filename has no way to tell a deliberate
// exclusion from a forgotten one. The reason is written above the entry when
// the die adds it, and is the same sentence the plan shows.
var markdownlintIgnores = []wanted{
	{
		line:   "CHANGELOG.md",
		reason: "regenerated by semantic-release on every release, so any normalization here is undone on the next one — and reappears as a conflict when a local commit lands on top of the release commit",
	},
}

type markdownlintignoreState struct {
	lineFile
	// hasChangelog sharpens the plan's wording rather than gating the entry:
	// seeding a repo before it cuts its first release is the point, since the
	// conflict this prevents shows up at exactly that moment.
	hasChangelog bool
	// releasable is the one thing that does gate it. Every entry here exists
	// because semantic-release regenerates a file and a local commit lands on
	// top of the release commit — which needs commits. A target git does not
	// version has no first release to be seeded before.
	releasable bool
}

func (s markdownlintignoreState) Summary() string {
	if !s.releasable {
		return "no releases here, so nothing to protect from one"
	}
	if !s.exists {
		return "no .markdownlintignore"
	}
	return fmt.Sprintf("markdownlintignore current (%s)", plural(len(s.lines), "line", "lines"))
}

func (Markdownlintignore) Observe(t reconcile.Target) (reconcile.Observation, error) {
	file, err := readLineFile(t.Path(".markdownlintignore"))
	if err != nil {
		return nil, err
	}

	_, err = os.Stat(t.Path("CHANGELOG.md"))
	if err != nil && !os.IsNotExist(err) {
		return nil, err
	}

	return markdownlintignoreState{lineFile: file, hasChangelog: err == nil, releasable: t.Versioned()}, nil
}

func (Markdownlintignore) Diff(_ reconcile.Target, observed reconcile.Observation) ([]reconcile.Change, error) {
	state, ok := observed.(markdownlintignoreState)
	if !ok {
		return nil, fmt.Errorf("markdownlintignore: unexpected observation %T", observed)
	}

	var changes []reconcile.Change
	if !state.releasable {
		return nil, nil
	}
	for _, entry := range markdownlintIgnores {
		switch count := state.count(entry.line); {
		case count == 0:
			detail := entry.reason
			if !state.hasChangelog {
				detail = "preventive — " + detail
			}
			changes = append(changes, reconcile.Change{
				Item:    entry.line,
				Verdict: reconcile.Missing,
				Repair:  reconcile.Automatic,
				Detail:  detail,
			})
		case count > 1:
			changes = append(changes, reconcile.Change{
				Item:     entry.line,
				Verdict:  reconcile.Stale,
				Repair:   reconcile.ByHand,
				Detail:   "listed more than once",
				Observed: fmt.Sprintf("%d occurrences", count),
			})
		}
	}

	return changes, nil
}

func (m Markdownlintignore) Perform(t reconcile.Target, change reconcile.Change) (reconcile.Outcome, error) {
	if !change.Actionable() {
		return reconcile.Outcome{Change: change, Status: reconcile.Refused, Message: "only a person can settle this one"}, nil
	}

	observed, err := m.Observe(t)
	if err != nil {
		return reconcile.Outcome{}, err
	}
	if observed.(markdownlintignoreState).count(change.Item) > 0 {
		return reconcile.Outcome{Change: change, Status: reconcile.Skipped, Message: "already present"}, nil
	}

	if err := appendBlock(t.Path(".markdownlintignore"), commentedEntry(change.Item), true); err != nil {
		return reconcile.Outcome{}, err
	}
	return reconcile.Outcome{Change: change, Status: reconcile.Done, Message: "added"}, nil
}

// commentedEntry renders the block written to the file: the reason as comment
// lines, then the entry itself.
func commentedEntry(item string) []string {
	for _, entry := range markdownlintIgnores {
		if entry.line != item {
			continue
		}
		block := make([]string, 0, 4)
		for _, line := range wrapComment(entry.reason, 76) {
			block = append(block, "# "+line)
		}
		return append(block, entry.line)
	}
	return []string{item}
}

// wrapComment breaks a reason into comment-width lines. Written out rather than
// left as one long line because these files are read by people, and the
// markdownlint hook has an opinion about line length in the repos that lint
// their own markdown.
func wrapComment(text string, width int) []string {
	var lines []string
	var current string

	for _, word := range splitWords(text) {
		switch {
		case current == "":
			current = word
		case len(current)+1+len(word) <= width:
			current += " " + word
		default:
			lines = append(lines, current)
			current = word
		}
	}
	if current != "" {
		lines = append(lines, current)
	}
	return lines
}

func splitWords(text string) []string {
	var words []string
	start := -1
	for i := range len(text) {
		if text[i] == ' ' {
			if start >= 0 {
				words = append(words, text[start:i])
				start = -1
			}
			continue
		}
		if start < 0 {
			start = i
		}
	}
	if start >= 0 {
		words = append(words, text[start:])
	}
	return words
}
